# Generated by Django 2.1 on 2018-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=256)),
                ('media_id', models.CharField(max_length=256)),
                ('appid', models.CharField(max_length=256)),
                ('pagepath', models.CharField(max_length=256)),
            ],
        ),
    ]
